spring:
  application:
    name: user-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      fail-fast: true

rental:
  service:
    url: http://localhost:8081